#! /usr/bin/env zsh

local _KPP_ALL_DIR="/Users/gosahai/workplace/KPPAll"

function kppui_build_full() {
    ((!$#)) && echo -e "[!]${cyan} Provide the project" && return
    local PROJECT_NAME=${1}
    local KPP_MAIN_APP_FRONT_END_PATH="${_KPP_ALL_DIR}/${PROJECT_NAME}/src/KPPMainAppFrontEnd"
    pushd -q "${KPP_MAIN_APP_FRONT_END_PATH}"
    echo -e "${lgreen}[!] Building Full KPPUI Project: ${PROJECT_NAME} | $(pwd)${NC}"
    brazil-recursive-cmd 'brazil-build' || {_print_err_ms; return 1}
    popd -q
}

function kppui_build2_partial() {
    ((!$#)) && echo -e "[!]${cyan} Provide the project" && return
    local PROJECT_NAME=${1}
    local KPP_MAIN_APP_FRONT_END_PATH="${_KPP_ALL_DIR}/${PROJECT_NAME}/src/KPPMainAppFrontEnd"
    pushd -q "${KPP_MAIN_APP_FRONT_END_PATH}"
    echo -e "${lgreen}[!] Building Partial KPPUI Project: ${PROJECT_NAME} | $(pwd)${NC}"
    npm run bundle:release:all
    # this creates hbc files(js) and mo files(locales)
    # npm run build
    # this creates only hbc files(js)
    npm run hermes-precompile:mainapp:release

    cp build/include/KPPMainApp.js.hbc build/eink-artifactory/app/KPPMainApp/js
    cp -r build/include/mo/* build/eink-artifactory/app/KPPMainApp/locale

    popd -q
}

function kppui_build_partial() {
    ((!$#)) && echo -e "[!]${cyan} Provide the project" && return
    local PROJECT_NAME=${1}
    local KPP_MAIN_APP_FRONT_END_PATH="${_KPP_ALL_DIR}/${PROJECT_NAME}/src/KPPMainAppFrontEnd"
    pushd -q "${KPP_MAIN_APP_FRONT_END_PATH}"
    echo -e "${lgreen}[!] Building Partial KPPUI Project: ${PROJECT_NAME} | $(pwd)${NC}"
    echo "Brazil build"
    brazil-build run-s bundle:release:all hermes-precompile:mainapp:release create-eink-artifact:js create-eink-artifact:res || {_print_err_ms; return 1}
    popd -q
}

function kppui_checks() {
    ((!$#)) && echo -e "[!]${cyan} Provide the project" && return
    local PROJECT_NAME=${1}
    local KPP_MAIN_APP_FRONT_END_PATH="${_KPP_ALL_DIR}/${PROJECT_NAME}/src/KPPMainAppFrontEnd"
    pushd -q "${KPP_MAIN_APP_FRONT_END_PATH}"
    echo -e "${lcyan}[!] Running KPPUI Checks on Project: ${PROJECT_NAME} | $(pwd)${NC}"

    npm run prettier
    npm run tsc

    popd -q
}

function kppui_deploy() {
    ((!$#)) && echo -e "[!]${cyan} Provide the project" && return
    local PROJECT_NAME=${1}
    local KPP_MAIN_APP_FRONT_END_BUILD_PATH="${_KPP_ALL_DIR}/${PROJECT_NAME}/src/KPPMainAppFrontEnd/build/eink-artifactory/app/KPPMainApp"
    echo -e "${lcyan}[!] Deploying KPPUI Project: ${PROJECT_NAME}"
    adb push ${KPP_MAIN_APP_FRONT_END_BUILD_PATH} /app
}

function kppui_bd_full() {
    ((!$#)) && echo -e "[!]${cyan} Provide the project" && return
    local PROJECT_NAME=${1}
    kppui_build_full ${PROJECT_NAME} || {_print_err_ms; return 1}
    kppui_deploy ${PROJECT_NAME} || {_print_err_ms; return 1}
}

function kppui_bd_partial() {
    ((!$#)) && echo -e "[!]${cyan} Provide the project" && return
    local PROJECT_NAME=${1}
    # kppui_checks ${PROJECT_NAME}
    kppui_build_partial ${PROJECT_NAME} || {_print_err_ms; return 1}
    kppui_deploy ${PROJECT_NAME} || {_print_err_ms; return 1}
}
