#! /usr/bin/env zsh

alias .='cd ..'
alias cc='cd ~/Codes/CPP/'
alias v='vim'
alias sl='ls'
alias ..='cd ..;cd ..'
alias ..g='cd $(git rev-parse --show-toplevel)'

alias sudo='sudo '

if is_mac; then
  alias l="gls -lahG --color"
  alias ls="gls -G --color"
  alias ll="gls -lhG --color"
fi
