#! /usr/bin/env zsh

alias .='cd ..'
alias cc='cd ~/Codes/CPP/'
alias v='vim'
alias sl='ls'
alias ..='cd ..;cd ..'
alias ..g='cd $(git rev-parse --show-toplevel)'
alias ssh="/usr/local/bin/ssh -oStrictHostKeyChecking=no"

alias sudo='sudo '

#copy
cz() {
  if is_linux; then
    echo "$($@)"|xclip -selection clipboard;
  elif is_mac; then
    echo "$($@)"|pbcopy;
  fi
}


