#! /usr/bin/env zsh

export GPG_TTY=$(tty)

getmac()
{
	curl https://api.macvendors.com/$1;
}

has_docker && archdocker() {
	local CONTAINER="${1}"
	[ "${CONTAINER}" = "" ] && CONTAINER="archdocker" 
	if [ ! "$(docker ps -a | grep ${CONTAINER})" ]; then
		echo "Creating new container in detached mode..."
		docker run -dit -d -v $HOME:/root --name ${CONTAINER} arch:0.1
	fi
	if [ "$(docker inspect -f '{{.State.Running}}' ${CONTAINER} 2> /dev/null)" = "false" ]; then
		echo "Starting container..."
		docker start ${CONTAINER}
	fi
	echo "Attaching to container..."
	docker attach ${CONTAINER}
}

lssh() {
	local HOST=${1}
	echo "While loop over ssh: ${HOST}"
	ssh ${HOST}
	while [ $? -ne 0 ]; do 
		sleep 1s; 
		ssh ${HOST}; 
	done
}
