#! /usr/bin/env zsh

is_mac() {
    [ "$(uname)" = "Darwin" ]
}

is_linux() {
    [ "$(uname)" = "Linux" ]
}

is_docker() {
    # https://stackoverflow.com/a/25518538/3789604
    [ -f /.dockerenv ]
}

is_archlinux() {
    # https://bbs.archlinux.org/viewtopic.php?id=82449
    [ -f "/etc/arch-release" ]
}

is_fullsystem() {
    ! is_docker
}

is_on_path() {
    local CMD=${1}
    command -v ${CMD} &> /dev/null
}

has_java() {
    is_on_path java
}

has_docker() {
    is_on_path docker
}

is_flipkart_mac() {
    is_mac && [[ $(hostname -s) =~ "g0vinds-LaP" ]]
}

