#! /usr/bin/env zsh

decryptAndMove() {
    local FILEX=${1}
    echo "[!] Processing File: ${FILEX}"
    local pan=$(get_PAN)
    local cmd="qpdf -password=${pan} -decrypt ${FILEX} outzzzz.pdf"
    echo "[!] Running: ${cmd}"
    eval ${cmd}
    local cmd="mv outzzzz.pdf ${FILEX}"
    echo "[!] Running: ${cmd}"
    eval ${cmd}
    open ${FILEX}
}
